project:
  type: website
  output-dir: docs

website:
  title: "Vitória Sesana"
  favicon: imagens/lavender.png
  navbar:
    logo: imagens/lavender.png
    title: "Vitória Sesana"
    background: "#AD96DC"
    foreground: "white" 
    right:
      # - text: Home
      #   href: index.qmd
      - text: Posts
        href: aba_posts/index.qmd
      - text: Sobre
        href: about.qmd
  page-footer: 
    background: "#AD96DC"
    foreground: "white"
    left: "© 2025" 
    right: 
      - icon: github
        href: https://github.com/vitoria-sesana
      - icon: linkedin
        href: https://www.linkedin.com/in/vit%C3%B3ria-sesana-836035174/
      - text: vitoria.nj.sesana@gmail.com
        # colocar tbm link do repositorio do website
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

